src/Web/ViewModels/OrderViewModel.cs
using Microsoft.eShopWeb.ApplicationCore.Entities.OrderAggregate;
using System;
using System.Collections.Generic;

namespace Microsoft.eShopWeb.Web.ViewModels
{
    public class OrderViewModel
    {
        public int OrderNumber { get; set; }
        public DateTimeOffset OrderDate { get; set; }
        public decimal Total { get; set; }
        public string Status { get; set; }

        public Address ShippingAddress { get; set; } 

        public List<OrderItemViewModel> OrderItems { get; set; } = new List<OrderItemViewModel>();

    }

}

src/Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.eShopWeb.Web.ViewModels;
using System;
using Microsoft.eShopWeb.ApplicationCore.Entities.OrderAggregate;
using Microsoft.eShopWeb.ApplicationCore.Interfaces;
using System.Linq;
using Microsoft.eShopWeb.ApplicationCore.Specifications;

namespace Microsoft.eShopWeb.Web.Controllers
{
    [Authorize]
    [Route("[controller]/[action]")]
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;

        public OrderController(IOrderRepository orderRepository) {
            _orderRepository = orderRepository;
        }
        
        public async Task<IActionResult> Index()
        {
            var orders = await _orderRepository.ListAsync(new CustomerOrdersWithItemsSpecification(User.Identity.Name));

            var viewModel = orders
                .Select(o => new OrderViewModel()
                {
                    OrderDate = o.OrderDate,
                    OrderItems = o.OrderItems?.Select(oi => new OrderItemViewModel()
                    {
                        Discount = 0,
                        PictureUrl = oi.ItemOrdered.PictureUri,
                        ProductId = oi.ItemOrdered.CatalogItemId,
                        ProductName = oi.ItemOrdered.ProductName,
                        UnitPrice = oi.UnitPrice,
                        Units = oi.Units
                    }).ToList(),
                    OrderNumber = o.Id,
                    ShippingAddress = o.ShipToAddress,
                    Status = "Pending",
                    Total = o.Total()

                });
            return View(viewModel);
        }

        [HttpGet("{orderId}")]
        public async Task<IActionResult> Detail(int orderId)
        {
            var customerOrders = await _orderRepository.ListAsync(new CustomerOrdersWithItemsSpecification(User.Identity.Name));
            var order = customerOrders.FirstOrDefault(o => o.Id == orderId);
            if (order == null)
            {
                return BadRequest("No such order found for this user.");
            }
            var viewModel = new OrderViewModel()
            {
                OrderDate = order.OrderDate,
                OrderItems = order.OrderItems.Select(oi => new OrderItemViewModel()
                {
                    Discount = 0,
                    PictureUrl = oi.ItemOrdered.PictureUri,
                    ProductId = oi.ItemOrdered.CatalogItemId,
                    ProductName = oi.ItemOrdered.ProductName,
                    UnitPrice = oi.UnitPrice,
                    Units = oi.Units
                }).ToList(),
                OrderNumber = order.Id,
                ShippingAddress = order.ShipToAddress,
                Status = "Pending",
                Total = order.Total()
            };
            return View(viewModel);
        }
    }
}

src/Web/Views/Order/Detail.cshtml
@using Microsoft.eShopWeb.Web.ViewModels
@model OrderViewModel
@{
    ViewData["Title"] = "My Order History";
}
@{
    ViewData["Title"] = "Order Detail";
}

<div class="esh-orders_detail">
    <div class="container">
        <section class="esh-orders_detail-section">
            <article class="esh-orders_detail-titles row">
                <section class="esh-orders_detail-title col-xs-3">Order number</section>
                <section class="esh-orders_detail-title col-xs-3">Date</section>
                <section class="esh-orders_detail-title col-xs-3">Total</section>
                <section class="esh-orders_detail-title col-xs-3">Status</section>
            </article>

            <article class="esh-orders_detail-items row">
                <section class="esh-orders_detail-item col-xs-3">@Model.OrderNumber</section>
                <section class="esh-orders_detail-item col-xs-3">@Model.OrderDate</section>
                <section class="esh-orders_detail-item col-xs-3">$@Model.Total</section>
                <section class="esh-orders_detail-title col-xs-3">@Model.Status</section>
            </article>
        </section>

        @*<section class="esh-orders_detail-section">
            <article class="esh-orders_detail-titles row">
                <section class="esh-orders_detail-title col-xs-12">Description</section>
            </article>

            <article class="esh-orders_detail-items row">
                <section class="esh-orders_detail-item col-xs-12">@Model.Description</section>
            </article>
        </section>*@

        <section class="esh-orders_detail-section">
            <article class="esh-orders_detail-titles row">
                <section class="esh-orders_detail-title col-xs-12">Shipping Address</section>
            </article>

            <article class="esh-orders_detail-items row">
                <section class="esh-orders_detail-item col-xs-12">@Model.ShippingAddress.Street</section>
            </article>

            <article class="esh-orders_detail-items row">
                <section class="esh-orders_detail-item col-xs-12">@Model.ShippingAddress.City</section>
            </article>

            <article class="esh-orders_detail-items row">
                <section class="esh-orders_detail-item col-xs-12">@Model.ShippingAddress.Country</section>
            </article>
        </section>

        <section class="esh-orders_detail-section">
            <article class="esh-orders_detail-titles row">
                <section class="esh-orders_detail-title col-xs-12">ORDER DETAILS</section>
            </article>

            @for (int i = 0; i < Model.OrderItems.Count; i++)
            {
                var item = Model.OrderItems[i];
                <article class="esh-orders_detail-items esh-orders_detail-items--border row">
                    <section class="esh-orders_detail-item col-md-4 hidden-md-down">
                        <img class="esh-orders_detail-image" src="@item.PictureUrl">
                    </section>
                    <section class="esh-orders_detail-item esh-orders_detail-item--middle col-xs-4">@item.ProductName</section>
                    <section class="esh-orders_detail-item esh-orders_detail-item--middle col-xs-1">$ @item.UnitPrice.ToString("N2")</section>
                    <section class="esh-orders_detail-item esh-orders_detail-item--middle col-xs-1">@item.Units</section>
                    <section class="esh-orders_detail-item esh-orders_detail-item--middle col-xs-2">$ @Math.Round(item.Units * item.UnitPrice, 2).ToString("N2")</section>
                </article>
            }
        </section>

        <section class="esh-orders_detail-section esh-orders_detail-section--right">
            <article class="esh-orders_detail-titles esh-basket-titles--clean row">
                <section class="esh-orders_detail-title col-xs-9"></section>
                <section class="esh-orders_detail-title col-xs-2">TOTAL</section>
            </article>

            <article class="esh-orders_detail-items row">
                <section class="esh-orders_detail-item col-xs-9"></section>
                <section class="esh-orders_detail-item esh-orders_detail-item--mark col-xs-2">$ @Model.Total</section>
            </article>
        </section>
    </div>
</div>

src/Web/Views/Order/Index.cshtml
@using Microsoft.eShopWeb.Web.ViewModels
@model IEnumerable<OrderViewModel>
@{
    ViewData["Title"] = "My Order History";
}

<div class="esh-orders">
    <div class="container">
        <h1>@ViewData["Title"]</h1>
        <article class="esh-orders-titles row">
            <section class="esh-orders-title col-xs-2">Order number</section>
            <section class="esh-orders-title col-xs-4">Date</section>
            <section class="esh-orders-title col-xs-2">Total</section>
            <section class="esh-orders-title col-xs-2">Status</section>
            <section class="esh-orders-title col-xs-2"></section>
        </article>
        @if (Model != null && Model.Any())
        {
            @foreach (var item in Model)
            {
                <article class="esh-orders-items row">
                    <section class="esh-orders-item col-xs-2">@Html.DisplayFor(modelItem => item.OrderNumber)</section>
                    <section class="esh-orders-item col-xs-4">@Html.DisplayFor(modelItem => item.OrderDate)</section>
                    <section class="esh-orders-item col-xs-2">$ @Html.DisplayFor(modelItem => item.Total)</section>
                    <section class="esh-orders-item col-xs-2">@Html.DisplayFor(modelItem => item.Status)</section>
                    <section class="esh-orders-item col-xs-1">
                        <a class="esh-orders-link" asp-controller="Order" asp-action="Detail" asp-route-orderId="@item.OrderNumber">Detail</a>
                    </section>
                    <section class="esh-orders-item col-xs-1">
                        @if (item.Status.ToLower() == "submitted")
                    {
                            <a class="esh-orders-link" asp-controller="Order" asp-action="cancel" asp-route-orderId="@item.OrderNumber">Cancel</a>
                        }
                    </section>
                </article>
            }
        }
    </div>
</div>